#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/clone/functions"

case "$1" in
  help | clone:help)
    help_content_func() {
      declare desc="return help_content string"
      cat<<help_content
    clone, creates/updates app from remote git repo
    clone:key, outputs the dokku public deploy key
    clone:allow, adds a domain to known_hosts
help_content
    }

    if [[ $1 = "gplive:help" ]] ; then
      echo -e 'Usage: dokku clone <app> <git-url>'
      echo ''
      echo 'Clones and builds remote repos into dokku app'
      echo ''
      echo 'Example:'
      echo ''
      echo '$ dokku clone nodeapp https://github.com/heroku/node-js-sample'
      echo ''
    else
      help_content_func
    fi
    ;;

  clone)
    clone_main_cmd "$@"
    ;;

  clone:key)
    clone_key_cmd "$@"
    ;;

  clone:allow)
    clone_allow_cmd "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
